export const AUTHORIZED_COUNTRIES = {
    "Tous les pays africains et îles périphériques, expt le pays de résidence": [
        "Afrique du Sud",
        "Algérie",
        "Angola",
        "Bénin",
        "Botswana",
        "Burkina Faso",
        "Burundi",
        "Cabo Verde (Cap-Vert)",
        "Cameroun",
        "Comores",
        "Congo (Brazzaville)",
        "Côte d'Ivoire",
        "Djibouti",
        "Égypte",
        "Érythrée",
        "Eswatini",
        "Éthiopie",
        "Gabon",
        "Gambie",
        "Ghana",
        "Guinée",
        "Guinée-Bissau",
        "Guinée équatoriale",
        "Kenya",
        "Lesotho",
        "Libéria",
        "Madagascar",
        "Malawi",
        "Maroc",
        "Maurice",
        "Mauritanie",
        "Mozambique",
        "Namibie",
        "Nigéria",
        "Ouganda",
        "République démocratique du Congo",
        "Rwanda",
        "Sao Tomé-et-Principe",
        "Sénégal",
        "Seychelles",
        "Sierra Leone",
        "Tanzanie",
        "Tchad",
        "Togo",
        "Tunisie",
        "Zambie",
        "Zimbabwe"
    ],
    "Tous les pays du continent européens et les îles périphériques": [
        "Allemagne",
        "Autriche",
        "Belgique",
        "Bulgarie",
        "Chypre",
        "Croatie",
        "Danemark",
        "Espagne",
        "Estonie",
        "Finlande",
        "France",
        "Grèce",
        "Hongrie",
        "Irlande",
        "Italie",
        "Lettonie",
        "Lituanie",
        "Luxembourg",
        "Malte",
        "Pays-Bas",
        "Pologne",
        "Portugal",
        "République tchèque",
        "Roumanie",
        "Slovaquie",
        "Slovénie",
        "Suède",
        "Islande",
        "Liechtenstein",
        "Norvège",
        "Suisse",
        "Royaume-Uni",
        "Albanie",
        "Andorre",
        "Bosnie-Herzégovine",
        "Kosovo",
        "Macédoine du Nord",
        "Moldavie",
        "Monaco",
        "Monténégro",
        "Saint-Marin",
        "Serbie",
        "Vatican"
    ],
    "Tous les pays membres de l’espace Schengen": [
        "Allemagne",
        "Autriche",
        "Belgique",
        "Bulgarie",
        "Croatie",
        "Danemark",
        "Espagne",
        "Estonie",
        "Finlande",
        "France",
        "Grèce",
        "Hongrie",
        "Islande",
        "Italie",
        "Lettonie",
        "Liechtenstein",
        "Lituanie",
        "Luxembourg",
        "Malte",
        "Norvège",
        "Pays-Bas",
        "Pologne",
        "Portugal",
        "République tchèque",
        "Roumanie",
        "Slovaquie",
        "Slovénie",
        "Suède",
        "Suisse"
    ],
    "Pèlerinage": [
        "Arabie Saoudite",
        "Jordanie",
        "Égypte",
        "Turquie",
        "Inde",
        "Népal",
        "Sri Lanka",
        "Tibet / Chine",
        "Japon",
        "Maroc",
        "Éthiopie",
        "Mexique",
        "Brésil",
        "Pérou",
        "États-Unis"
    ],
    "Tous les pays du monde entier, expt le pays de résidence": [
        "Couverture"
    ]
}